[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/aftership-webhook"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/aftership-webhook"
  status = 200
